### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Bagel7723** [GlacierPark19/CTI-Foods#1]
Some parts of this project use code and images from https://github.com/MatrexsVigil/harvestcraft and/or https://github.com/MatrexsVigil/phc2crops. This is a violation of the copyright for these projects as they do not use an open-source license. (Anything from https://github.com/cweckerl/simplefarming doesn't apply.) It is stated in the about section of these projects 'None of my artwork is available to be used for FREE in your game EVER.'

The assets taken from these projects should be replaced ASAP to avoid any potential issues.

**Comment by GlacierPark19** [comment]
Fix in progress

**Comment by Bagel7723** [comment]
I don't think the issue should be closed until the issue is actually fixed.
